<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>Judo</AssemblyName>
    <RootNamespace>Judo</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Foundation\Address.cs" Link="Address.cs" />
    <Compile Include="..\Foundation\AgeCategory.cs" Link="AgeCategory.cs" />
    <Compile Include="..\Foundation\Belt.cs" Link="Belt.cs" />
    <Compile Include="..\Foundation\Category.cs" Link="Category.cs" />
    <Compile Include="..\Foundation\Club.cs" Link="Club.cs" />
    <Compile Include="..\Foundation\EmailAddress.cs" Link="EmailAddress.cs" />
    <Compile Include="..\Foundation\Enums.cs" Link="Enums.cs" />
    <Compile Include="..\Foundation\Mat.cs" Link="Mat.cs" />
    <Compile Include="..\Foundation\Match.cs" Link="Match.cs" />
    <Compile Include="..\Foundation\Name.cs" Link="Name.cs" />
    <Compile Include="..\Foundation\Nation.cs" Link="Nation.cs" />
    <Compile Include="..\Foundation\Person.cs" Link="Person.cs" />
    <Compile Include="..\Foundation\PhoneNumber.cs" Link="PhoneNumber.cs" />
    <Compile Include="..\Foundation\Player.cs" Link="Player.cs" />
    <Compile Include="..\Foundation\Rank.cs" Link="Rank.cs" />
    <Compile Include="..\Foundation\Score.cs" Link="Score.cs" />
    <Compile Include="..\Foundation\ScoreboardData.cs" Link="ScoreboardData.cs" />
    <Compile Include="..\Foundation\Technique.cs" Link="Technique.cs" />
    <Compile Include="..\Foundation\UDPSegment.cs" Link="UDPSegment.cs" />
    <Compile Include="..\Foundation\Weight.cs" Link="Weight.cs" />
    <Compile Include="..\Foundation\WeightCategory.cs" Link="WeightCategory.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="4.5.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Utilities\Utilities.csproj" />
  </ItemGroup>

</Project>
