//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MappingTool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GeneralImportFilename {
            get {
                return ((string)(this["GeneralImportFilename"]));
            }
            set {
                this["GeneralImportFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GeneralImportHeaders {
            get {
                return ((bool)(this["GeneralImportHeaders"]));
            }
            set {
                this["GeneralImportHeaders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GeneralImportRemoveTotalRow {
            get {
                return ((bool)(this["GeneralImportRemoveTotalRow"]));
            }
            set {
                this["GeneralImportRemoveTotalRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",")]
        public string GeneralImportDelimiter {
            get {
                return ((string)(this["GeneralImportDelimiter"]));
            }
            set {
                this["GeneralImportDelimiter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\my_ippon.org\\events")]
        public string IJFExportFolder {
            get {
                return ((string)(this["IJFExportFolder"]));
            }
            set {
                this["IJFExportFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reference\\Clubs.csv")]
        public string ReferenceClubsFilename {
            get {
                return ((string)(this["ReferenceClubsFilename"]));
            }
            set {
                this["ReferenceClubsFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reference\\Countries.csv")]
        public string ReferenceCountriesFilename {
            get {
                return ((string)(this["ReferenceCountriesFilename"]));
            }
            set {
                this["ReferenceCountriesFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\EuroJudo\\Tournaments.mdb")]
        public string EuroJudoDatabaseFilename {
            get {
                return ((string)(this["EuroJudoDatabaseFilename"]));
            }
            set {
                this["EuroJudoDatabaseFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\EuroJudo\\Data\\Members & Clubs for import.xls")]
        public string EuroJudoExportFilename {
            get {
                return ((string)(this["EuroJudoExportFilename"]));
            }
            set {
                this["EuroJudoExportFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reference\\SubDivisions.csv")]
        public string ReferenceSubDivisionsFilename {
            get {
                return ((string)(this["ReferenceSubDivisionsFilename"]));
            }
            set {
                this["ReferenceSubDivisionsFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("66")]
        public double EuroJudoEventValueMinimumComparison {
            get {
                return ((double)(this["EuroJudoEventValueMinimumComparison"]));
            }
            set {
                this["EuroJudoEventValueMinimumComparison"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public double EuroJudoWeightValueMinimumComparison {
            get {
                return ((double)(this["EuroJudoWeightValueMinimumComparison"]));
            }
            set {
                this["EuroJudoWeightValueMinimumComparison"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("33")]
        public double BeltValueMinimumComparison {
            get {
                return ((double)(this["BeltValueMinimumComparison"]));
            }
            set {
                this["BeltValueMinimumComparison"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("33")]
        public double EuroJudoGenderValueMinimumComparison {
            get {
                return ((double)(this["EuroJudoGenderValueMinimumComparison"]));
            }
            set {
                this["EuroJudoGenderValueMinimumComparison"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("66")]
        public double EuroJudoClubValueMinimumComparison {
            get {
                return ((double)(this["EuroJudoClubValueMinimumComparison"]));
            }
            set {
                this["EuroJudoClubValueMinimumComparison"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>O</string>
  <string>&gt;</string>
  <string>over</string>
  <string>Over</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection EuroJudoWeightCategoryOverReplacement {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EuroJudoWeightCategoryOverReplacement"]));
            }
            set {
                this["EuroJudoWeightCategoryOverReplacement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>U</string>
  <string>&lt;</string>
  <string>under</string>
  <string>Under</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection EuroJudoWeightCategoryUnderReplacement {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EuroJudoWeightCategoryUnderReplacement"]));
            }
            set {
                this["EuroJudoWeightCategoryUnderReplacement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+")]
        public string EuroJudoWeightCategoryOverValue {
            get {
                return ((string)(this["EuroJudoWeightCategoryOverValue"]));
            }
            set {
                this["EuroJudoWeightCategoryOverValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-")]
        public string EuroJudoWeightCategoryUnderValue {
            get {
                return ((string)(this["EuroJudoWeightCategoryUnderValue"]));
            }
            set {
                this["EuroJudoWeightCategoryUnderValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT DISTINCT [Game Index], Tournament FROM [Tournament Data] ORDER BY [Game In" +
            "dex]")]
        public string EuroJudoTournamentQuery {
            get {
                return ((string)(this["EuroJudoTournamentQuery"]));
            }
            set {
                this["EuroJudoTournamentQuery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT [Event Nr], [Genus], [Group] FROM [Tournament Data] WHERE [Game Index] = #" +
            "#SelectedEuroJudoTournament_Index## ORDER BY [Event Nr]")]
        public string EuroJudoEventQuery {
            get {
                return ((string)(this["EuroJudoEventQuery"]));
            }
            set {
                this["EuroJudoEventQuery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT [Class Nr], [Group], [Weight Category], [Lower Limit], [Upper Limit] FROM " +
            "[Weight Categories] WHERE [Game Index] = ##SelectedEuroJudoTournament_Index## OR" +
            "DER BY [Class Nr]")]
        public string EuroJudoWeightQuery {
            get {
                return ((string)(this["EuroJudoWeightQuery"]));
            }
            set {
                this["EuroJudoWeightQuery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PreviousEuroJudoTournament {
            get {
                return ((string)(this["PreviousEuroJudoTournament"]));
            }
            set {
                this["PreviousEuroJudoTournament"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int PreviousEuroJudoEventTypeColumnIndex {
            get {
                return ((int)(this["PreviousEuroJudoEventTypeColumnIndex"]));
            }
            set {
                this["PreviousEuroJudoEventTypeColumnIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int PreviousEuroJudoWeightCategoryColumnIndex {
            get {
                return ((int)(this["PreviousEuroJudoWeightCategoryColumnIndex"]));
            }
            set {
                this["PreviousEuroJudoWeightCategoryColumnIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int PreviousClubColumnIndex {
            get {
                return ((int)(this["PreviousClubColumnIndex"]));
            }
            set {
                this["PreviousClubColumnIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int PreviousMemberIDColumnIndex {
            get {
                return ((int)(this["PreviousMemberIDColumnIndex"]));
            }
            set {
                this["PreviousMemberIDColumnIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int PreviousYearOfBirthColumnIndex {
            get {
                return ((int)(this["PreviousYearOfBirthColumnIndex"]));
            }
            set {
                this["PreviousYearOfBirthColumnIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int PreviousGenderColumnIndex {
            get {
                return ((int)(this["PreviousGenderColumnIndex"]));
            }
            set {
                this["PreviousGenderColumnIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int PreviousBeltColumnIndex {
            get {
                return ((int)(this["PreviousBeltColumnIndex"]));
            }
            set {
                this["PreviousBeltColumnIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int PreviousFirstNameColumnIndex {
            get {
                return ((int)(this["PreviousFirstNameColumnIndex"]));
            }
            set {
                this["PreviousFirstNameColumnIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int PreviousSurnameColumnIndex {
            get {
                return ((int)(this["PreviousSurnameColumnIndex"]));
            }
            set {
                this["PreviousSurnameColumnIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int PreviousEuroJudoDayOfBirthColumnIndex {
            get {
                return ((int)(this["PreviousEuroJudoDayOfBirthColumnIndex"]));
            }
            set {
                this["PreviousEuroJudoDayOfBirthColumnIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int PreviousFirstNameTranslationType {
            get {
                return ((int)(this["PreviousFirstNameTranslationType"]));
            }
            set {
                this["PreviousFirstNameTranslationType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int PreviousSurnameTranslationType {
            get {
                return ((int)(this["PreviousSurnameTranslationType"]));
            }
            set {
                this["PreviousSurnameTranslationType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int PreviousMemberIDTranslationType {
            get {
                return ((int)(this["PreviousMemberIDTranslationType"]));
            }
            set {
                this["PreviousMemberIDTranslationType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int PreviousEuroJudoDayOfBirthTranslationType {
            get {
                return ((int)(this["PreviousEuroJudoDayOfBirthTranslationType"]));
            }
            set {
                this["PreviousEuroJudoDayOfBirthTranslationType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int PreviousEuroJudoMonthOfBirthTranslationType {
            get {
                return ((int)(this["PreviousEuroJudoMonthOfBirthTranslationType"]));
            }
            set {
                this["PreviousEuroJudoMonthOfBirthTranslationType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int PreviousEuroJudoYearOfBirthTranslationType {
            get {
                return ((int)(this["PreviousEuroJudoYearOfBirthTranslationType"]));
            }
            set {
                this["PreviousEuroJudoYearOfBirthTranslationType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public double EuroJudoFunctionValueMinimumComparison {
            get {
                return ((double)(this["EuroJudoFunctionValueMinimumComparison"]));
            }
            set {
                this["EuroJudoFunctionValueMinimumComparison"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int PreviousEuroJudoFunctionColumnIndex {
            get {
                return ((int)(this["PreviousEuroJudoFunctionColumnIndex"]));
            }
            set {
                this["PreviousEuroJudoFunctionColumnIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int PreviousDateOfBirthColumnIndex {
            get {
                return ((int)(this["PreviousDateOfBirthColumnIndex"]));
            }
            set {
                this["PreviousDateOfBirthColumnIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SERVER=localhost;UID=your_user;DATABASE=ippon_org_db;PORT=3306")]
        public string IJFDatabaseConnectionString {
            get {
                return ((string)(this["IJFDatabaseConnectionString"]));
            }
            set {
                this["IJFDatabaseConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PreviousIJFTournament {
            get {
                return ((string)(this["PreviousIJFTournament"]));
            }
            set {
                this["PreviousIJFTournament"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT event_id, event_name FROM ippon_org_db.tta_events;")]
        public string IJFTournamentQuery {
            get {
                return ((string)(this["IJFTournamentQuery"]));
            }
            set {
                this["IJFTournamentQuery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PreviousOutputType {
            get {
                return ((string)(this["PreviousOutputType"]));
            }
            set {
                this["PreviousOutputType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>O</string>
  <string>&gt;</string>
  <string>over</string>
  <string>Over</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection IJFWeightCategoryOverReplacement {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["IJFWeightCategoryOverReplacement"]));
            }
            set {
                this["IJFWeightCategoryOverReplacement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+")]
        public string IJFWeightCategoryOverValue {
            get {
                return ((string)(this["IJFWeightCategoryOverValue"]));
            }
            set {
                this["IJFWeightCategoryOverValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>U</string>
  <string>&lt;</string>
  <string>under</string>
  <string>Under</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection IJFWeightCategoryUnderReplacement {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["IJFWeightCategoryUnderReplacement"]));
            }
            set {
                this["IJFWeightCategoryUnderReplacement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-")]
        public string IJFWeightCategoryUnderValue {
            get {
                return ((string)(this["IJFWeightCategoryUnderValue"]));
            }
            set {
                this["IJFWeightCategoryUnderValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public double IJFWeightValueMinimumComparison {
            get {
                return ((double)(this["IJFWeightValueMinimumComparison"]));
            }
            set {
                this["IJFWeightValueMinimumComparison"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public double IJFFunctionValueMinimumComparison {
            get {
                return ((double)(this["IJFFunctionValueMinimumComparison"]));
            }
            set {
                this["IJFFunctionValueMinimumComparison"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int PreviousIJFFunctionColumnIndex {
            get {
                return ((int)(this["PreviousIJFFunctionColumnIndex"]));
            }
            set {
                this["PreviousIJFFunctionColumnIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT event_age_group, event_gender, event_cat_m, event_cat_w FROM ippon_org_db." +
            "tta_events\n WHERE event_name = \'##SelectedIJFTournament_Name##\';")]
        public string IJFWeightQuery {
            get {
                return ((string)(this["IJFWeightQuery"]));
            }
            set {
                this["IJFWeightQuery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int PreviousIJFWeightCategoryColumnIndex {
            get {
                return ((int)(this["PreviousIJFWeightCategoryColumnIndex"]));
            }
            set {
                this["PreviousIJFWeightCategoryColumnIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int PreviousIJFPhotoColumnIndex {
            get {
                return ((int)(this["PreviousIJFPhotoColumnIndex"]));
            }
            set {
                this["PreviousIJFPhotoColumnIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\my_ippon.org\\my_pics")]
        public string IJFUserPhotoSaveFolder {
            get {
                return ((string)(this["IJFUserPhotoSaveFolder"]));
            }
            set {
                this["IJFUserPhotoSaveFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GeneralImportRemoveLateFeeTotalRow {
            get {
                return ((bool)(this["GeneralImportRemoveLateFeeTotalRow"]));
            }
            set {
                this["GeneralImportRemoveLateFeeTotalRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IJFPhotoFilenameIsMemberID {
            get {
                return ((bool)(this["IJFPhotoFilenameIsMemberID"]));
            }
            set {
                this["IJFPhotoFilenameIsMemberID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AUS")]
        public string GeneralClubDefaultCountryCode {
            get {
                return ((string)(this["GeneralClubDefaultCountryCode"]));
            }
            set {
                this["GeneralClubDefaultCountryCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GeneralShowDataInfoWindow {
            get {
                return ((bool)(this["GeneralShowDataInfoWindow"]));
            }
            set {
                this["GeneralShowDataInfoWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\xampp\\htdocs\\ippon.org\\data\\pics")]
        public string IJFSystemPhotoSaveFolder {
            get {
                return ((string)(this["IJFSystemPhotoSaveFolder"]));
            }
            set {
                this["IJFSystemPhotoSaveFolder"] = value;
            }
        }
    }
}
