//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Designer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("66")]
        public double EuroJudoEventValueMinimumComparison {
            get {
                return ((double)(this["EuroJudoEventValueMinimumComparison"]));
            }
            set {
                this["EuroJudoEventValueMinimumComparison"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public double EuroJudoWeightValueMinimumComparison {
            get {
                return ((double)(this["EuroJudoWeightValueMinimumComparison"]));
            }
            set {
                this["EuroJudoWeightValueMinimumComparison"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>O</string>
  <string>&gt;</string>
  <string>over</string>
  <string>Over</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection EuroJudoWeightCategoryOverReplacement {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EuroJudoWeightCategoryOverReplacement"]));
            }
            set {
                this["EuroJudoWeightCategoryOverReplacement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>U</string>
  <string>&lt;</string>
  <string>under</string>
  <string>Under</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection EuroJudoWeightCategoryUnderReplacement {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EuroJudoWeightCategoryUnderReplacement"]));
            }
            set {
                this["EuroJudoWeightCategoryUnderReplacement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+")]
        public string EuroJudoWeightCategoryOverValue {
            get {
                return ((string)(this["EuroJudoWeightCategoryOverValue"]));
            }
            set {
                this["EuroJudoWeightCategoryOverValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-")]
        public string EuroJudoWeightCategoryUnderValue {
            get {
                return ((string)(this["EuroJudoWeightCategoryUnderValue"]));
            }
            set {
                this["EuroJudoWeightCategoryUnderValue"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT DISTINCT [Game Index], Tournament FROM [Tournament Data] ORDER BY [Game In" +
            "dex]")]
        public string EuroJudoTournamentQuery {
            get {
                return ((string)(this["EuroJudoTournamentQuery"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT [Event Nr], [Genus], [Group] FROM [Tournament Data] WHERE [Game Index] = #" +
            "#SelectedEuroJudoTournament_Index## ORDER BY [Event Nr]")]
        public string EuroJudoEventQuery {
            get {
                return ((string)(this["EuroJudoEventQuery"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT [Class Nr], [Group], [Weight Category] FROM [Weight Categories] WHERE [Gam" +
            "e Index] = ##SelectedEuroJudoTournament_Index## ORDER BY [Class Nr]")]
        public string EuroJudoWeightQuery {
            get {
                return ((string)(this["EuroJudoWeightQuery"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double EuroJudoClubValueMinimumComparison {
            get {
                return ((double)(this["EuroJudoClubValueMinimumComparison"]));
            }
            set {
                this["EuroJudoClubValueMinimumComparison"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\YourUser\\OneDrive\\Documents\\Judo\\Tournaments\\Tournaments.mdb")]
        public string EuroJudoDatabaseFilename {
            get {
                return ((string)(this["EuroJudoDatabaseFilename"]));
            }
            set {
                this["EuroJudoDatabaseFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\YourUser\\OneDrive\\VS Projects\\Revolutionise\\Samples\\euro.xls")]
        public string EuroJudoExportFilename {
            get {
                return ((string)(this["EuroJudoExportFilename"]));
            }
            set {
                this["EuroJudoExportFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\YourUser\\OneDrive\\VS Projects\\Revolutionise\\Samples\\Clubs.csv")]
        public string EuroJudoClubsFilename {
            get {
                return ((string)(this["EuroJudoClubsFilename"]));
            }
            set {
                this["EuroJudoClubsFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\YourUser\\OneDrive\\VS Projects\\Revolutionise\\Samples\\Countries.csv")]
        public string EuroJudoCountriesFilename {
            get {
                return ((string)(this["EuroJudoCountriesFilename"]));
            }
            set {
                this["EuroJudoCountriesFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\YourUser\\OneDrive\\VS Projects\\Revolutionise\\Samples\\SubDivisions.csv")]
        public string EuroJudoSubDivisionsFilename {
            get {
                return ((string)(this["EuroJudoSubDivisionsFilename"]));
            }
            set {
                this["EuroJudoSubDivisionsFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastEuroJudoTournament {
            get {
                return ((string)(this["LastEuroJudoTournament"]));
            }
            set {
                this["LastEuroJudoTournament"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\YourUser\\OneDrive\\VS Projects\\Revolutionise\\Samples\\revolutioniseSPORT-Judo" +
            "WA-Anothertest.csv")]
        public string ImportFilename {
            get {
                return ((string)(this["ImportFilename"]));
            }
            set {
                this["ImportFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int LastEuroJudoEventTypeColumnIndex {
            get {
                return ((int)(this["LastEuroJudoEventTypeColumnIndex"]));
            }
            set {
                this["LastEuroJudoEventTypeColumnIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int LastEuroJudoWeightCategoryColumnIndex {
            get {
                return ((int)(this["LastEuroJudoWeightCategoryColumnIndex"]));
            }
            set {
                this["LastEuroJudoWeightCategoryColumnIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int LastEuroJudoClubColumnIndex {
            get {
                return ((int)(this["LastEuroJudoClubColumnIndex"]));
            }
            set {
                this["LastEuroJudoClubColumnIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ImportFileHasHeaders {
            get {
                return ((bool)(this["ImportFileHasHeaders"]));
            }
            set {
                this["ImportFileHasHeaders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RemoveTotalRowFromImport {
            get {
                return ((bool)(this["RemoveTotalRowFromImport"]));
            }
            set {
                this["RemoveTotalRowFromImport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",")]
        public string LastImportDelimiter {
            get {
                return ((string)(this["LastImportDelimiter"]));
            }
            set {
                this["LastImportDelimiter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IJFExportFilename {
            get {
                return ((string)(this["IJFExportFilename"]));
            }
            set {
                this["IJFExportFilename"] = value;
            }
        }
    }
}
